### ISSUE TITLE
Sync Fail

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/webuildthis.city#22]
@briaguya 
Email received: 
Can you help us?
 
Jaime was trying to update this page http://permittingatx.com/residential/residential-toolkit/check-my-application-status/ but both of us are getting a syncing failure. Attached is a screenshot. When we click on Update Source we get a permissions warning. Any insights?
 
Appreciate it,
 
Rachel Crist
Public Information Specialist Sr.
<img width="1440" alt="e759ade3-e512-4906-9573-4a604cb6db26" src="https://user-images.githubusercontent.com/35745454/40803353-465802b6-64cd-11e8-850e-c649ad093f51.png">

**Comment by benweatherman** [comment]
Based on the suggestion in the error, I've been trying to remove and reconnect the repo but can't find suitable credentials for adding the connection with a shared github account.

**Comment by benweatherman** [comment]
It looks like CloudCannon hasn't been syncing with GitHub since August. This definitely isn't a critical error, the site will continue to be published as usual.

Once the above referenced pull request is merged, we can setup the syncing again.

**Comment by benweatherman** [comment]
All changes in CloudCannon should be syncing to GitHub now. We should have the fine folks at DSD give the content a once-over to make sure their latest changes are deployed.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/272675/40847898-342eb420-6583-11e8-83f3-43dd905c7369.png">
