### ISSUE TITLE
Set up content editing experience

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/webuildthis.city#5]
Deploy an interface that we can show to stakeholders to start the conversation going about editing content. 

Questions to consider:
- Can Siteleaf handle _data editing? 
- Could something else?

Also, talk to the Dev Team to get feedback about the challenges of Siteleaf and arguments for other options.

**Comment by sknep** [comment]
I checked out CloudCannon last night and I really prefer it over siteleaf. I think we'll use that instead!

**Comment by patrickm02L** [comment]
See #6
